###############################################################################################################################################################################
# This is a GitHub Actions workflow file. It is written in YAML and specifies a series of commands that execute when certain events occur. Currently, all jobs in this file are
# running on an Ubuntu Linux host.
#
# This file is responsible for running the ESLint static code analyzer on the repository on each push to the "main" branch. To accomplish this, the "Action ESLint" GitHub
# Action is used. For the "main" branch, the pipeline is as follows:
#
#   * repository-checkout - Checks out the "main" branch for Pocket Fic and uploads the repository as an artifact
#   * eslint-report       - Run ESLint on the project and uploads "eslint-report.html" as an artifact
#
# {@link https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions | Introduction to GitHub Actions}
# {@link https://github.com/actions/virtual-environments | GitHub Actions Virtual Environments}
# {@link https://github.com/marketplace/actions/action-eslint | Action ESLint GitHub Action}
###############################################################################################################################################################################

name : ESLint

# Triggers The Workflow On "pull_request" and "push" Events But Only For The "main" Branch
on :
  pull_request :
    branches : [main]
  push :
    branches : [main]

  # Allows The Workflow To Run Manually If Needed From The "Actions" Tab
  workflow_dispatch :

jobs:
  ########## JOB 1 - REPOSITORY CHECKOUT ##########
  repository-checkout :
    runs-on : ubuntu-latest

    steps :
      - name : Configuration
        run : |
          echo "--------------------------------------------- ENVIRONMENT INFORMATION ---------------------------------------------"
          echo "GitHub Event Name:              "${{ github.event_name }}
          echo "GitHub API URL:                 "$GITHUB_API_URL
          echo "GitHub GraphQL API URL:         "$GITHUB_GRAPHQL_URL
          echo "GitHub Server URL:              "$GITHUB_SERVER_URL
          echo "Workflow Branch:                "$GITHUB_REF
          echo "Workflow URL:                   "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
          echo "Workflow WebHook Event:         "$GITHUB_EVENT_NAME
          echo "Workflow WebHook Event Payload: "$GITHUB_EVENT_PATH
          echo "Workflow Repository:            "$GITHUB_REPOSITORY
          echo "Workflow Initiator:             "$GITHUB_ACTOR
          echo "Workflow Run ID:                "$GITHUB_RUN_ID
          echo "Workflow Run Number:            "$GITHUB_RUN_NUMBER
          echo "Workflow Name:                  "$GITHUB_WORKFLOW
          echo "Workspace:                      "$GITHUB_WORKSPACE
          echo ""
          echo "See https://docs.github.com/en/actions/reference/environment-variables"

          echo "------------------------------------------------ RUNNER INFORMATION -----------------------------------------------"
          echo "Runner Operating System:    "${{ runner.os }}
          echo "Runner Temporary Directory: "${{ runner.temp }}
          echo "Runner Tools:               "${{ runner.tool_cache }}
          echo "-------------------------------------------------------------------------------------------------------------------"
          git config --global init.defaultBranch main

      - name : Commit Snapshot — SHA-224 ${{ github.sha }}
        uses : actions/checkout@v3
        with :
          path : ""
          repository : ${{ github.repository }}
          token : ${{ github.token }}
          ref : main
          clean : true
          lfs : false
          persist-credentials : true
          ssh-strict : true
          submodules : true
          fetch-depth : 0 # Fetches All History For All Branches And Tags

      - name : Upload Repository Snapshot Artifact — "Pocket-Fic"
        uses : actions/upload-artifact@v3
        with :
          name : Pocket-Fic
          path : "/home/runner/work/Pocket-Fic/Pocket-Fic"
          retention-days : 5

  ########## JOB 2 - ESLINT REPORT ##########
  eslint-report :
    needs : repository-checkout
    runs-on : ubuntu-latest
    strategy :
      matrix :
        node-version : [16.X]

    steps :
      - name : Setup Node.js LTS ${{ matrix.node-version }}
        uses : actions/setup-node@v3
        with :
          node-version : ${{ matrix.node-version }}

      - name : Commit Snapshot — SHA-224 ${{ github.sha }}
        uses : actions/download-artifact@v3
        with :
          name : Pocket-Fic

      - name : Determine If "node_modules" Cache Is Usable Based On Changes To "package.json" And "package-lock.json"...
        id : node-modules-cache
        uses : actions/cache@v3
        with :
          path : "/home/runner/work/Pocket-Fic/Pocket-Fic/node_modules"
          key : ${{ matrix.node-version }}-node-modules-${{ hashFiles('**/package*.json') }}

      - name : Install npm Dependencies If Required
        # Caches Older Than Five Days (GitHub Setting) Are Evicted Based On Age Or If The 5 GB Cache Limit Exceeded
        if : steps.node-modules-cache.outputs.cache-hit != 'true'
        run : |
          echo "Installing Dependencies Defined In "package-lock.json" Using npm... This May Take A While..."
          npm install

      - name : Run ESLint
        uses : sibiraj-s/action-eslint@v2
        with :
          annotations : true
          eslint-args : "-f node_modules/eslint-html-reporter/reporter.js -o ./eslint-report.html"
          extensions : "ts"

      - name : Upload ESLint Linting Artifact — "eslint-report"
        uses : actions/upload-artifact@v3
        with :
          name : eslint-report
          path : "/home/runner/work/Pocket-Fic/Pocket-Fic/eslint-report.html"
          retention-days : 5
