######################################################################################################################################################
# Copyright 2021 Evan H. Harding. All Rights Reserved.
#
# This is a GitHub Actions workflow file. It is written in YAML and specifies a series of commands that execute when certain events occur. Currently,
# all jobs in this file are running on an Ubuntu Linux host. See https://github.com/actions/virtual-environments for a list of options.
#
#   * repository-checkout - Checks out The `main` GitHub repository branch for Fan Fiction.com and uploads the repository artifact for future use
#   * install-build-test  - Downloads Node.js (and NPM)
#                         - Downloads the repository snapshot artifact from the previous job
#                         - Installs necessary NPM dependencies
#                         |--> Caches node_modules for future use
#                         - Runs a production build and uploads `dist` as an artifact
#                         - Runs ESLint checks
#
# {@link https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions | Introduction to GitHub Actions}
######################################################################################################################################################

name : Fan Fiction.com

on :
  # Triggers The Workflow On `push` Events But Only For The `main` Branch
  push :
    branches : [main]

  # Allows The Workflow To Be Run Manually From The `Actions` Tab
  workflow_dispatch :

jobs :
  ########## JOB 1 - REPOSITORY-CHECKOUT ##########
  repository-checkout :
    runs-on : ${{ matrix.os }}
    strategy :
      matrix :
        os :
        - ubuntu-latest

    steps :
      - name: Configure Git Initial Branch Name
        run: git config --global init.defaultBranch main

      - name : Checkout Repository
        uses : actions/checkout@v2
        with :
          path : ''
          repository : ${{ github.repository }}
          token : ${{ github.token }}
          ref : main
          clean : true
          lfs : false
          persist-credentials : true
          ssh-strict : true
          submodules : true
          fetch-depth : 0

      - name : Upload Repository Snapshot Artifact
        uses : actions/upload-artifact@v2
        with :
          name : fan-fiction-dot-com
          path : '/home/runner/work/FanFiction.com/FanFiction.com'

  ########## JOB 2 - INSTALL-BUILD-TEST ##########
  install-build-test :
    needs : repository-checkout
    runs-on : ${{ matrix.os }}
    strategy :
      matrix :
        node-version : [15.10.0]
        os :
          - ubuntu-latest

    steps :
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name : Download Repository Snapshot
        uses : actions/download-artifact@v2
        with :
          name : fan-fiction-dot-com

      - name : Cache `node_modules`
        id : node-modules-cache
        uses : actions/cache@v2
        with :
          path : '/home/runner/work/FanFiction.com/FanFiction.com/node_modules'
          key : ${{ matrix.node-version }}-node-modules

      - name : Install NPM Dependencies
        if : steps.node-modules-cache.outputs.cache-hit != 'true'
        run : |
          echo 'Installing Dependencies Defined In `package.json` Using NPM... This May Take Awhile'
          npm install

      - name : Run Production Build
        run : |
          echo 'Starting Up The Angular Framework...'

          npm run ng
          npm run build:prod

      - name : Upload `dist` Production Build Artifact
        uses : actions/upload-artifact@v2
        with :
          name : dist-prod
          path : '/home/runner/work/FanFiction.com/FanFiction.com/dist'
