######################################################################################################################################################
# Copyright 2021 Evan H. Harding. All Rights Reserved.
#
# This is a GitHub Actions workflow file. It is written in YAML and specifies a series of commands that execute when certain events occur. Jobs
# consist of the following:
#
#   * BUILD - Builds and tests the project in a CI/CD environment.
#
# {@link https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions | Introduction to GitHub Actions}
######################################################################################################################################################

name : Fan Fiction.com CI Angular Build And Test

on :
  # Triggers The Workflow On `push` Events But Only For The `main` Branch
  push :
    branches :
      - main

  # Allows The Workflow To Be Run Manually From The `Actions` Tab
  workflow_dispatch :

jobs :
  ########## JOB 1 - BUILD ##########
  build :
    runs-on : self-hosted
    strategy :
      matrix :
        node-version : [15.10.0]

    steps :
      - name : Checkout Repository
        uses : actions/checkout@v2
        with :
          repository : ${{ github.repository }}
          ref : main
          clean : true
          lfs : false
          persist-credentials : true
          submodules : false
          path : ''

      - name : Node.js ${{ matrix.node-version }} Setup
        uses : actions/setup-node@v1
        with :
          node-version : ${{ matrix.node-version }}

      - name : NPM Install And NPM Build
        run : |
          npm run build:ci
