######################################################################################################################################################
# Copyright 2021 Evan H. Harding. All Rights Reserved.
#
# This is a GitHub Actions workflow file. It is written in YAML and specifies a series of commands that execute when certain events occur. Jobs
# consist of the following:
#
#   * initialize-environment - Initializes an Ubuntu Virtual Environment Runner on GitHub.
#                            - Checks Out The `main` GitHub Repository Branch For Fan Fiction.com.
#                            - Installs Node.js and NPM so that we can retrieve all dependencies and build the application.
#                            - Uploads the artifacts of the job for the next job.
#
# {@link https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions | Introduction to GitHub Actions}
######################################################################################################################################################

name : Fan Fiction.com CI Angular Build And Test

on :
  # Triggers The Workflow On `push` Events But Only For The `main` Branch
  push :
    branches :
      - main

  # Allows The Workflow To Be Run Manually From The `Actions` Tab
  workflow_dispatch :

jobs :
  ########## JOB 1 - initialize-environment ##########
  initialize-environment :
    runs-on : ${{ matrix.os }}
    strategy :
      matrix :
        node-version : [15.10.0]
        os :
          - ubuntu-latest

    steps :
      - name : Configure Git Initial Branch Name
        run : git config --global init.defaultBranch main

      - name : Repository Checkout
        uses : actions/checkout@v2
        with :
          path : ''
          repository : ${{ github.repository }}
          token : ${{ github.token }}
          ref : main
          clean : true
          lfs : false
          persist-credentials : true
          ssh-strict : true
          submodules : true
          fetch-depth : 0

      - name : Node.js ${{ matrix.node-version }} Setup
        uses : actions/setup-node@v2
        with :
          node-version : ${{ matrix.node-version }}

      - name : Git Configuration Artifact Upload
        uses : actions/upload-artifact@v2
        with :
          name : git-configuration
          path : .git
